FROM node:alpine

RUN apk --no-cache add openjdk11 bash curl nginx gettext sed grep

RUN npm install -g firebase-tools

WORKDIR /app

COPY emulator/firebase.json /app
RUN firebase setup:emulators:firestore
RUN firebase setup:emulators:ui

COPY emulator/serve.sh /usr/bin/
COPY emulator/data /app/data

EXPOSE 4000
EXPOSE 9150

#CMD [ "firebase", "--project=xrechnung-app", "emulators:start", "--only", "firestore" ]
ENTRYPOINT "/usr/bin/serve.sh"
